# Generated by Django 3.1.6 on 2021-02-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='class_standard',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='roll_number',
            field=models.IntegerField(),
        ),
    ]
