# Generated by Django 3.1.6 on 2021-02-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20210222_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('occupation', models.CharField(max_length=255)),
            ],
        ),
    ]
