# Generated by Django 3.1.6 on 2021-02-25 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_parent_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent_detail',
            old_name='name1',
            new_name='name',
        ),
    ]
