# Generated by Django 3.1.6 on 2021-02-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20210225_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent_detail',
            old_name='name',
            new_name='parent_name',
        ),
    ]
