# Generated by Django 3.1.6 on 2021-02-23 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AAA', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Items',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='name',
            new_name='item',
        ),
    ]
